### ISSUE TITLE
Add Lat/Lng coordinates for ICBs to allow for easier mapping

### ISSUE THREAD

**Issue by Amirjab21** [nhsbsa-data-analytics/medicines-used-in-mental-health#6]
Is it possible to add data for the ICB lat/lng boundaries so that people can easily put this data on a visual map?

**Comment by nhsbsa-grali** [comment]
This issue has been resolved by email, we have duplicated the response here in case it is helpful for other users. 

The pipeline code in its current form does not use latitude or longitude coordinates for Integrated Care Boards (ICBs), so there are no plans to add these. Data on ICB boundaries including latitude and longitude is available on the [Office For National Statistics (ONS) open geography portal website](https://geoportal.statistics.gov.uk/).
